apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-pricing
resources:
  - ../../base
images:
  - name: gitlab.andrea-house.com:5050/root/model-pricing/api
    newTag: latest
  - name: gitlab.andrea-house.com:5050/root/model-pricing/web
    newTag: latest
