apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-pricing
resources:
  - ../../base
patches:
  - target: { kind: Deployment, name: api }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target: { kind: Deployment, name: web }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
images:
  - name: gitlab.andrea-house.com:5050/root/model-pricing/api
    newTag: 0.1.0
  - name: gitlab.andrea-house.com:5050/root/model-pricing/web
    newTag: 0.1.0
