apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-pricing
resources:
  - ../../base
images:
  - name: ghcr.io/andreab67/ai-models-pricing/api
    newTag: latest
  - name: ghcr.io/andreab67/ai-models-pricing/web
    newTag: latest
